// <auto-generated />
using System;
using ExcelTask.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExcelTask.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220511190040_AddRelations")]
    partial class AddRelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExcelTask.Models.DateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Dates", (string)null);
                });

            modelBuilder.Entity("ExcelTask.Models.HourAndData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AirHumidity")
                        .HasColumnType("integer");

                    b.Property<int>("DateDataId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Hour")
                        .HasColumnType("time without time zone");

                    b.Property<int>("IdDate")
                        .HasColumnType("integer");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DateDataId");

                    b.ToTable("Data", (string)null);
                });

            modelBuilder.Entity("ExcelTask.Models.HourAndData", b =>
                {
                    b.HasOne("ExcelTask.Models.DateData", "DateData")
                        .WithMany("HourAndDatas")
                        .HasForeignKey("DateDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DateData");
                });

            modelBuilder.Entity("ExcelTask.Models.DateData", b =>
                {
                    b.Navigation("HourAndDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
